apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-lag-service
  labels:
    app: monitor-lag-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor-lag-service
  template:
    metadata:
      labels:
        app: monitor-lag-service
    spec:
      containers:
        - name: monitor-lag-service
          image: monitor-lag-service:1.0.0
          envFrom:
            - configMapRef:
                name: monitor-lag-service-config
            - secretRef:
                name: monitor-lag-service-secret
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
