server:
  port: 8080

logging:
  # Garante que o logback-spring.xml seja usado
  config: classpath:logback-spring.xml
  level:
    # Reduz o nível de verbosidade do Spring Cloud Gateway de DEBUG para INFO.
    # Isso eliminará a maioria dos logs internos detalhados do framework.
    org.springframework.cloud.gateway: INFO
    # Garante que o restante do Spring e o Reactor Netty permaneçam em INFO (padrão)
    org.springframework: INFO
    reactor.netty: INFO

# === CONFIGURAÇÃO ACTUATOR / MANAGEMENT ===
management:
  endpoints:
    web:
      # Expõe todos os endpoints do Actuator via web (O 'gateway' está incluído aqui)
      exposure:
        include: "*"
  # Adicionalmente, expõe todos os endpoints para monitoramento interno (se necessário)
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 5s

resilience4j:
  circuitbreaker:
    instances:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 4s

  timelimiter:
    instances:
      default:
        timeout-duration: 5s

  retry:
    instances:
      default:
        max-attempts: 3
        wait-duration: 200ms