global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files: []

scrape_configs:
  # ============================================================
  # PROMETHEUS SELF MONITORING
  # ============================================================
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  # ============================================================
  # NODE EXPORTER (metrics do host)
  # ============================================================
  - job_name: node-exporter
    static_configs:
      - targets: ["node-exporter:9100"]

  # ============================================================
  # BLACKBOX EXPORTER
  # ============================================================
  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://ecommerce-gateway:8080/actuator/health
          - http://product-service:8081/actuator/health
          - http://inventory-service:8082/actuator/health
          - http://cart-service:8083/actuator/health
          - http://order-service:8084/actuator/health
          - http://payment-service:8085/actuator/health
          - http://notification-service:8086/actuator/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  # ============================================================
  # OTEL COLLECTOR METRICS
  # ============================================================
  - job_name: otel-collector
    static_configs:
      - targets: ["otel-collector:8888"]

  # ============================================================
  # SPRING BOOT ACTUATORS – MONITORING STACK
  # ============================================================
  - job_name: spring-actuators
    metrics_path: /actuator/prometheus
    scrape_interval: 15s
    static_configs:
      - targets:
          - monitor-state-manager:8080
          - monitor-health-service:8080
          - monitor-lag-service:8080
          - monitor-consumer-presence-service:8080
          - monitor-alert-dispatcher:8080
