spring:
  application:
    name: cart-service

  datasource:
    url: jdbc:h2:mem:cart-servicedb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      group-id: cart-service-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

services:
  inventory: ${INVENTORY_SERVICE_URL:http://localhost:8080}


server:
  port: 8083
  
