global:
  resolve_timeout: 5m

route:
  receiver: default-receiver

receivers:
  - name: default-receiver
    webhook_configs:
      - url: http://monitor-alert-dispatcher:8092/alerts
        max_alerts: 10
