spring:
  application:
    name: monitor-health-service

monitor:
  local-json-path: ${MONITOR_LOCAL_JSON_PATH:}
  default-timeout-ms: 2000
  refresh-interval-seconds: 300

logging:
  level:
    root: INFO
    io.viana.monitor_health_service: DEBUG

server:
  port: 8091




# spring:
#   application:
#     name: monitor-health-service

# monitor:
#   targets:
#     - name: product-service
#       url: http://localhost:8081/actuator/health
#     - name: inventory-service
#       url: http://localhost:8082/actuator/health
#     - name: cart-service
#       url: http://localhost:8083/actuator/health
#     - name: order-service
#       url: http://localhost:8084/actuator/health
#     - name: payment-service
#       url: http://localhost:8085/actuator/health
#     - name: notification-service
#       url: http://localhost:8086/actuator/health
#     - name: ecommerce-gateway
#       url: http://localhost:8080/actuator/health

#   interval-seconds: 15
#   timeout-ms: 2000
#   state-manager-url: http://localhost:8090/state/health

# logging:
#   level:
#     root: INFO
#     io.viana.monitor_health_service: DEBUG

# server:
#   port: 8091

# ---
# spring:
#   config:
#     activate:
#       on-profile: docker
# monitor:

#   targets:
#     - name: product-service
#       url: http://product-service:8081/actuator/health
#     - name: inventory-service
#       url: http://inventory-service:8082/actuator/health
#     - name: cart-service
#       url: http://cart-service:8083/actuator/health
#     - name: order-service
#       url: http://order-service:8084/actuator/health
#     - name: payment-service
#       url: http://payment-service:8085/actuator/health
#     - name: notification-service
#       url: http://notification-service:8086/actuator/health
#     - name: ecommerce-gateway
#       url: http://ecommerce-gateway:8080/actuator/health

#   state-manager-url: ${MONITOR_STATE_MANAGER_URL}